[package]
name = "i2cdev-bno055"
version = "0.1.0"
authors = ["Benjamin Cheng <ben@bcheng.cf>"]
description = "BNO855 Absolute Orientation Sensor (Accelerometer, Gyroscope, Magnetometer)"

[dependencies]
byteorder = "1"
i2cdev = "0.3.1"
i2csensors = "0.1.2"
